global:
  image: {}
  connectors: {}

image: 
  name: "magda-csv-connector"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  tag: 0.0.57-0
  pullPolicy: IfNotPresent
  # imagePullSecret: ""

resources:
  requests:
    cpu: 50m
    memory: 30Mi
  limits:
    cpu: 100m

defaultSettings:
  includeInitialJobs: false
  includeCronJobs: true

# Chart level .Values.includeInitialJobs is higher priority than 
# .Values.global.includeInitialJobs
# The value of includeInitialJobs or includeCronJobs is determined by:
# - .Values.includeInitialJobs if its value is set
# - Then .Values.global.includeInitialJobs if its value is set
# - Then .Values.defaultSettings.includeInitialJobs
# By default, .Values.includeInitialJobs is not set. 
# Therefore, if .Values.global.includeInitialJobs is not set, .Values.defaultSettings.includeInitialJobs will be used.

#includeInitialJobs: false
#includeCronJobs: true

defaultTenantId: 0

config:
  ## Unique id to identify this connector and records that are harvested from it
  id: default-csv-connector

  ## Friendly readable name
  ## name: Default CSV Connector
  
  ## The base URL of the place (e.g. content-api) to download CSV file from
  # sourceUrl: 